# coding: utf-8
from sqlalchemy import BigInteger, Column, Float, MetaData, Table, Text

metadata = MetaData()


t_printings = Table(
    'printings', metadata,
    Column('index', BigInteger, index=True),
    Column('id', BigInteger),
    Column('artist', Text),
    Column('asciiName', Text),
    Column('availability', Text),
    Column('boosterTypes', Text),
    Column('borderColor', Text),
    Column('cardKingdomEtchedId', Text),
    Column('cardKingdomFoilId', Text),
    Column('cardKingdomId', Text),
    Column('cardParts', Text),
    Column('cardsphereId', Text),
    Column('colorIdentity', Text),
    Column('colorIndicator', Text),
    Column('colors', Text),
    Column('convertedManaCost', Float(53)),
    Column('duelDeck', Text),
    Column('edhrecRank', Float(53)),
    Column('faceConvertedManaCost', Float(53)),
    Column('faceFlavorName', Text),
    Column('faceManaValue', Float(53)),
    Column('faceName', Text),
    Column('finishes', Text),
    Column('flavorName', Text),
    Column('flavorText', Text),
    Column('frameEffects', Text),
    Column('frameVersion', Text),
    Column('hand', Text),
    Column('hasAlternativeDeckLimit', BigInteger),
    Column('hasContentWarning', BigInteger),
    Column('hasFoil', BigInteger),
    Column('hasNonFoil', BigInteger),
    Column('isAlternative', BigInteger),
    Column('isFullArt', BigInteger),
    Column('isFunny', BigInteger),
    Column('isOnlineOnly', BigInteger),
    Column('isOversized', BigInteger),
    Column('isPromo', BigInteger),
    Column('isRebalanced', BigInteger),
    Column('isReprint', BigInteger),
    Column('isReserved', BigInteger),
    Column('isStarter', BigInteger),
    Column('isStorySpotlight', BigInteger),
    Column('isTextless', BigInteger),
    Column('isTimeshifted', BigInteger),
    Column('keywords', Text),
    Column('language', Text),
    Column('layout', Text),
    Column('leadershipSkills', Text),
    Column('life', Text),
    Column('loyalty', Text),
    Column('manaCost', Text),
    Column('manaValue', Float(53)),
    Column('mcmId', Text),
    Column('mcmMetaId', Text),
    Column('mtgArenaId', Text),
    Column('mtgjsonV4Id', Text),
    Column('mtgoFoilId', Text),
    Column('mtgoId', Text),
    Column('multiverseId', Text),
    Column('name', Text),
    Column('number', Text),
    Column('originalPrintings', Text),
    Column('originalReleaseDate', Text),
    Column('originalText', Text),
    Column('originalType', Text),
    Column('otherFaceIds', Text),
    Column('power', Text),
    Column('printings', Text),
    Column('promoTypes', Text),
    Column('purchaseUrls', Text),
    Column('rarity', Text),
    Column('rebalancedPrintings', Text),
    Column('scryfallId', Text),
    Column('scryfallIllustrationId', Text),
    Column('scryfallOracleId', Text),
    Column('securityStamp', Text),
    Column('setCode', Text),
    Column('side', Text),
    Column('signature', Text),
    Column('subtypes', Text),
    Column('supertypes', Text),
    Column('tcgplayerEtchedProductId', Text),
    Column('tcgplayerProductId', Text),
    Column('text', Text),
    Column('toughness', Text),
    Column('type', Text),
    Column('types', Text),
    Column('uuid', Text),
    Column('variations', Text),
    Column('watermark', Text),
    schema='CardData'
)
