FROM python


RUN apt-get update && apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN wget https://mtgjson.com/api/v5/AllPrintings.sqlite

COPY . .

RUN chmod a+x run.sh

#RUN python createDBSchema.py
RUN python nameGenerator.py

CMD ["./run.sh"]


